---
version: '3.3'

services: 
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /var/docker/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Malermeisterx4gm
      - MYSQL_PASSWORD=Malermeisterx4gm
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    volumes: 
    # - nextcloud:/var/www/html
      - /media/HDD1/DATA:/usr/local/DATA
      - /media/HDD1/RAID:/data
    links:
      - nextcloud-db
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:marthacloud.com" # URL entsprechend anpassen!
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
      - default
    
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
